language: erlang
matrix:
    include:
      - otp_release: 23
      - otp_release: 22.3
      - otp_release: 21.3
      - otp_release: 20.3
      - otp_release: 19.3
      - otp_release: 18.3
        dist: trusty
install:
  - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3
script:
  - make
  - make test
  - make xref
  - make edoc
  - make dialyzer
sudo: false
notifications:
  email:
    recipients:
      - zotonic-commits@googlegroups.com
    on_success: change #[always|never|change] # default: change
    on_failure: always #[always|never|change] # default: always
